~terraform planまでをcomposite actionに切り出し

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,78 +20,81 @@ jobs:
         id: checkout
         uses: actions/checkout@v3
 
-      - name: Configure AWS credentials
-        id: configure-aws-credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-region: ap-northeast-1
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-github-actions
+      - uses: './.github/actions/terraform-plan'
 
-      - name: Get caller identity
-        id: get-caller-identity
-        run: aws sts get-caller-identity
-        shell: bash
 
-      - name: Get current Terraform version
-        id: get-terraform-version
-        run: echo "TERRAFORM_VERSION=$(cat .terraform-version)" >> $GITHUB_ENV
+      # - name: Configure AWS credentials
+      #   id: configure-aws-credentials
+      #   uses: aws-actions/configure-aws-credentials@v1
+      #   with:
+      #     aws-region: ap-northeast-1
+      #     role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-github-actions
 
-      - name: Setup Terraform
-        id: setup-terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_version: ${{ env.TERRAFORM_VERSION }}
+      # - name: Get caller identity
+      #   id: get-caller-identity
+      #   run: aws sts get-caller-identity
+      #   shell: bash
 
-      - name: Terraform Format
-        id: fmt
-        working-directory: "main"
-        run: terraform fmt -recursive -check
+      # - name: Get current Terraform version
+      #   id: get-terraform-version
+      #   run: echo "TERRAFORM_VERSION=$(cat .terraform-version)" >> $GITHUB_ENV
 
-      - name: Terraform Init
-        id: init
-        working-directory: "main"
-        run: terraform init
+      # - name: Setup Terraform
+      #   id: setup-terraform
+      #   uses: hashicorp/setup-terraform@v1
+      #   with:
+      #     terraform_version: ${{ env.TERRAFORM_VERSION }}
 
-      - name: Terraform Validate
-        id: validate
-        working-directory: "main"
-        run: terraform validate -no-color
+      # - name: Terraform Format
+      #   id: fmt
+      #   working-directory: "main"
+      #   run: terraform fmt -recursive -check
 
-      - name: Terraform Plan
-        id: plan
-        working-directory: "main"
-        shell: bash
-        run: terraform plan -no-color
-        continue-on-error: true
+      # - name: Terraform Init
+      #   id: init
+      #   working-directory: "main"
+      #   run: terraform init
 
-      - name: Terraform Plan (failure)
-        uses: actions/github-script@v6
-        if: steps.plan.outcome == 'failure'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-            </details>
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+      # - name: Terraform Validate
+      #   id: validate
+      #   working-directory: "main"
+      #   run: terraform validate -no-color
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan
+      #   id: plan
+      #   working-directory: "main"
+      #   shell: bash
+      #   run: terraform plan -no-color
+      #   continue-on-error: true
+
+      # - name: Terraform Plan (failure) -> GitHub Script
+      #   uses: actions/github-script@v6
+      #   if: steps.plan.outcome == 'failure'
+      #   env:
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+      #       <details><summary>Show Plan</summary>
+      #       \`\`\`\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
+      #       </details>
+      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
+
+      # - name: Terraform Plan (failure) -> Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
       - name: Terraform Apply
         working-directory: "main"
